//! Verification framework for the Torc language.
//!
//! Integrates SMT solvers (Z3/CVC5), structural analysis, abstract interpretation,
//! and proof caching to discharge proof obligations generated by contracts and types.
