//! Verification framework for the Torc language.
//!
//! Integrates structural analysis, abstract interpretation (interval domain),
//! SMT solvers (Z3, feature-gated), proof caching, and reporting to discharge
//! proof obligations generated by contracts and types.

pub mod cache;
pub mod engine;
pub mod interval;
pub mod profile;
pub mod registry;
pub mod report;
pub mod smt;
pub mod structural;
pub mod witness;

/// Whether Z3 SMT solver support is compiled in.
#[cfg(feature = "z3")]
pub const Z3_AVAILABLE: bool = true;
/// Whether Z3 SMT solver support is compiled in.
#[cfg(not(feature = "z3"))]
pub const Z3_AVAILABLE: bool = false;
